// hello-vue/src/components/Home.vue
<template>
  <Hello name="Romain" />
  <Counter />
  <Counter />
  <CounterJSX />
  <CounterJSX />
  <Select
    :values="['red', 'green', 'blue']"
    :selected="color"
    @selectedChange="updateColor"
  />
  <p>Vous avez sélectionné : {{ color }}</p>
</template>

<script>
import Hello from './components/Hello.vue';
import Counter from './components/Counter.vue';
import CounterJSX from './components/CounterJSX.vue';
import Select from './components/Select.vue';

export default {
  name: 'Home',
  components: {
    Hello,
    Counter,
    CounterJSX,
    Select,
  },
  data() {
    return {
      color: 'green',
    };
  },
  methods: {
    updateColor(color) {
      this.color = color;
    },
  },
};
</script>

// hello-angular/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  title = 'hello-angular';
  couleur = 'green';

  constructor() { }

  ngOnInit(): void {
  }

}

<app-hello></app-hello>
<app-hello name="Toto"></app-hello>
<app-hello [name]="'Toto'.toUpperCase()"></app-hello>
<app-hello [name]="title"></app-hello>

<app-counter></app-counter>
<app-counter></app-counter>
<app-counter></app-counter>

<app-ex-helloworld></app-ex-helloworld>
<app-ex-multistate-button [values]="['red', 'green', 'blue']"></app-ex-multistate-button>

<app-select [values]="['red', 'green', 'blue']" [(selected)]="couleur"></app-select>

<p>Vous avez sélectionné : {{couleur}}</p>
